<?php

namespace App\Http\Controllers;

use App\Enums\WorkspaceRole;
use App\Http\Requests\StoreCurrencyRequest;
use App\Http\Requests\StoreOnboardingInviteRequest;
use App\Http\Requests\StoreWorkspaceRequest;
use App\Models\User;
use App\Models\Workspace;
use App\Models\WorkspaceInvitation;
use App\Notifications\WorkspaceInvitationNotification;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Str;
use Inertia\Inertia;
use Inertia\Response;

class OnboardingController extends Controller
{
    public function createWorkspace(): Response
    {
        return Inertia::render('onboarding/CreateWorkspace');
    }

    public function storeWorkspace(StoreWorkspaceRequest $request): RedirectResponse
    {
        /** @var User $user */
        $user = $request->user();

        // Slug is auto-generated by the Workspace model's booted() method via generateUniqueSlug()
        $workspace = Workspace::create(['name' => $request->validated('name')]);

        $user->workspaces()->attach($workspace->id, ['role' => 'owner']);
        session(['active_workspace_id' => $workspace->id]);

        setPermissionsTeamId($workspace->id);
        $user->assignRole('owner');

        return redirect()->route('onboarding.invite');
    }

    public function invite(): Response
    {
        return Inertia::render('onboarding/Invite');
    }

    public function storeInvite(StoreOnboardingInviteRequest $request): RedirectResponse
    {
        $email = $request->input('emails');

        if ($email) {
            $workspace = app(Workspace::class);

            /** @var int $expiry */
            $expiry = config('workspace.invitation_expiry_hours');

            $invitation = WorkspaceInvitation::create([
                'workspace_id' => $workspace->id,
                'email' => $email,
                'role' => WorkspaceRole::Member->value,
                'token' => Str::random(64),
                'expires_at' => now()->addHours($expiry),
            ]);

            Notification::route('mail', $invitation->email)
                ->notify(new WorkspaceInvitationNotification($invitation));
        }

        return redirect()->route('onboarding.currency');
    }

    public function currency(): Response
    {
        return Inertia::render('onboarding/Currency');
    }

    public function storeCurrency(StoreCurrencyRequest $request): RedirectResponse
    {
        /** @var string $currency */
        $currency = $request->validated('currency');

        $workspace = app(Workspace::class);
        $workspace->update(['currency' => strtoupper($currency)]);

        return redirect()->route('dashboard');
    }
}
