<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCurrencyRequest;
use App\Http\Requests\StoreWorkspaceRequest;
use App\Models\User;
use App\Models\Workspace;
use Illuminate\Http\RedirectResponse;
use Inertia\Inertia;
use Inertia\Response;

class OnboardingController extends Controller
{
    public function createWorkspace(): Response
    {
        return Inertia::render('onboarding/CreateWorkspace');
    }

    public function storeWorkspace(StoreWorkspaceRequest $request): RedirectResponse
    {
        /** @var User $user */
        $user = $request->user();

        // Slug is auto-generated by the Workspace model's booted() method via generateUniqueSlug()
        $workspace = Workspace::create(['name' => $request->validated('name')]);

        $user->workspaces()->attach($workspace->id, ['role' => 'owner']);
        session(['active_workspace_id' => $workspace->id]);

        return redirect()->route('onboarding.invite');
    }

    public function invite(): Response
    {
        return Inertia::render('onboarding/Invite');
    }

    public function storeInvite(): RedirectResponse
    {
        // Invitation emails handled in Task #8 - skip for now
        return redirect()->route('onboarding.currency');
    }

    public function currency(): Response
    {
        return Inertia::render('onboarding/Currency');
    }

    public function storeCurrency(StoreCurrencyRequest $request): RedirectResponse
    {
        /** @var string $currency */
        $currency = $request->validated('currency');

        $workspace = app(Workspace::class);
        $workspace->update(['currency' => strtoupper($currency)]);

        return redirect()->route('dashboard');
    }
}
